export const PRODUCTSREPO = 'PRODUCTS_REPOSITORY';
export const DEPARTMENTSREPO = 'DEPARTMENTS_REPOSITORY';
export const CATEGORIESREPO = 'CATEGORIES_REPOSITORY';
export const SIZESREPO = 'SIZES_REPOSITORY';
