version: "3"

services:
  backend:
    build: "./back"
    ports:
      - 3333:3333
    volumes:
      - ../backend:/usr/src/app

  frontend:
    build: "./front"
    ports:
      - 5000:5000
    volumes:
      - ../frontend:/usr/src/app
