version: "3.7"

services:
  backend:
    build: "./back"
    ports:
      - 3000:3000
    volumes:
      - ../backend:/usr/src/app

  frontend:
    build: "./front"
    ports:
      - 5000:5000
    volumes:
      - ../frontend:/usr/src/app
