name: Unit Tests (Coverage)

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Collect coverage
        run: yarn test:back > OUT; sed -n 6,8p OUT > .github/workflows/COVERAGE_REPORT
        env:
          DB_HOST: db-mysql-nyc3-51803-do-user-9201426-0.b.db.ondigitalocean.com
          DB_PORT: 25060
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_DIALECT: mysql
          DB_NAME_TEST: tests
          DB_NAME_STAGING: staging
          DB_NAME_PRODUCTION: defaultdb

      - uses: harupy/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: COVERAGE_REPORT
